### ISSUE TITLE
[feature suggest] change background color

### ISSUE THREAD

**Issue by thangckt** [j3lte/vscode-folder-customization#1]
Dear @j3lte 

Is it possible to change background color of folder?
Something like this:

![image](https://github.com/user-attachments/assets/7c4603e6-1ed1-4f03-8206-9f32d304ab5e)

Thank you.

**Comment by j3lte** [comment]
Unfortunately that level of customization is not possible in VSCode, we can only set the text color and an icon. There are a few colored squares you could use as emoji icon (search for `square`) to make it easily identifiable.
